export enum Sender {
  USER = 'user',
  BOT = 'bot',
  SYSTEM = 'system'
}

export interface Message {
  id: string;
  text: string;
  sender: Sender;
  timestamp: Date;
  isThinking?: boolean;
  relatedToolOutput?: string; // To show the "Moses" query result in UI for demo purposes
}

export interface Ticket {
  id: string;
  merchantName: string;
  subject: string;
  status: 'Open' | 'Pending' | 'Resolved';
  priority: 'Low' | 'Medium' | 'High';
  aiDiagnosis: string; // The "Private Note" generated by AI
  chatHistory: Message[];
  createdAt: Date;
}

export interface MosesLogResult {
  sr: number; // Success Rate (0-100)
  fra_blocks: number;
  api_failures: number;
  last_error_code: string | null;
  status: 'HEALTHY' | 'CRITICAL' | 'WARNING';
}

export enum MosesQueryType {
  TRANSACTION_STATS = 'TRANSACTION_STATS',
  FRA_BLOCKS = 'FRA_BLOCKS',
  INTEGRATION_HEALTH = 'INTEGRATION_HEALTH'
}